/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_mishlabs_q_Q */

#ifndef _Included_com_mishlabs_q_Q
#define _Included_com_mishlabs_q_Q
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_version
     * Signature: ()Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_mishlabs_q_Q_native_1version
    (JNIEnv *, jobject);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_connect
     * Signature: ()J
     */
    JNIEXPORT jlong JNICALL Java_com_mishlabs_q_Q_native_1connect
    (JNIEnv *, jobject);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_disconnect
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_com_mishlabs_q_Q_native_1disconnect
    (JNIEnv *, jobject, jlong);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_post
     * Signature: (JLjava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_mishlabs_q_Q_native_1post
    (JNIEnv *, jobject, jlong, jstring, jstring, jlong);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_worker
     * Signature: (JLjava/lang/String;Lcom/mishlabs/q/NativeWorker;)V
     */
    JNIEXPORT void JNICALL Java_com_mishlabs_q_Q_native_1worker
    (JNIEnv *, jobject, jlong, jstring, jobject);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_observer
     * Signature: (JLjava/lang/String;Lcom/mishlabs/q/NativeObserver;)V
     */
    JNIEXPORT void JNICALL Java_com_mishlabs_q_Q_native_1observer
    (JNIEnv *, jobject, jlong, jstring, jobject);
    
#ifdef __cplusplus
}
#endif
#endif
