// config.h is generated by autoreconf / configure
#include "../../config.h"

#ifdef JNI_HEADER

#include JNI_HEADER

/* Header for class com_mishlabs_q_Q */

#ifndef __q__QlibJava__
#define __q__QlibJava__

extern "C"
{
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_version
     * Signature: ()Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_mishlabs_q_Q_native_1version
    (JNIEnv *, jobject);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_connect
     * Signature: (Ljava/lang/String;)J
     */
    JNIEXPORT jlong JNICALL Java_com_mishlabs_q_Q_native_1connect
    (JNIEnv *, jobject, jstring);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_disconnect
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_com_mishlabs_q_Q_native_1disconnect
    (JNIEnv *, jobject, jlong);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_post
     * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_mishlabs_q_Q_native_1post
    (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jlong);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_reschedule
     * Signature: (JLjava/lang/String;J)Z
     */
    JNIEXPORT jboolean JNICALL Java_com_mishlabs_q_Q_native_1reschedule
    (JNIEnv *, jobject, jlong, jstring, jlong);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_cancel
     * Signature: (JLjava/lang/String;)Z
     */
    JNIEXPORT jboolean JNICALL Java_com_mishlabs_q_Q_native_1cancel
    (JNIEnv *, jobject, jlong, jstring);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_worker
     * Signature: (JLjava/lang/String;Lcom/mishlabs/q/NativeWorker;)V
     */
    JNIEXPORT void JNICALL Java_com_mishlabs_q_Q_native_1worker
    (JNIEnv *, jobject, jlong, jstring, jobject);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_observer
     * Signature: (JLjava/lang/String;Lcom/mishlabs/q/NativeObserver;)V
     */
    JNIEXPORT void JNICALL Java_com_mishlabs_q_Q_native_1observer
    (JNIEnv *, jobject, jlong, jstring, jobject);

    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_clear
     * Signature: (JLjava/lang/String;)Z
     */
    JNIEXPORT void JNICALL Java_com_mishlabs_q_Q_native_1clear
    (JNIEnv *, jobject, jlong, jstring);
    
    /*
     * Class:     com_mishlabs_q_Q
     * Method:    native_drop
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_com_mishlabs_q_Q_native_1drop
    (JNIEnv *, jobject, jlong);

}
#endif /* defined(__q__QlibJava__) */

#endif /*JNI_HEADER*/